plugins:
  - prettier-plugin-java
  - prettier-plugin-apex

# Prettier (formatter) configuration
printWidth: 120
tabWidth: 4
useTabs: false
semi: false
singleQuote: true
trailingComma: none
bracketSpacing: true
arrowParens: avoid
bracketSameLine: true
endOfLine: lf

Overrides:
  - files: "*.java"
    options:
      parser: "java"
  - files: "*.cls"
    options:
      parser: "apex"
  - files: "*.trigger"
    options:
      parser: "apex"
  - files: "/lwc/**/*.html"
    options:
      parser: "lwc"
  - files: "/lwc/**/*.js"
    options:
      parser: "lwc"
  - files: "*.{html,cmp,page,component}"
    options:
     parser: "html"
  - files: "*.json"
    options:
      parser: "json"
  - files: "*.xml"
    options:
      parser: "xml"
  - files: "*.yml"
    options:
     parser: "yaml"
  - files: "*.css"
    options:
     parser: "css"