CREATE DATABASE RestaurantDB;
USE RestaurantDB;
-- Create tables:
CREATE TABLE CUSTOMER
(
    Customer_ID INT NOT NULL,
    First_Name VARCHAR(50),
    Last_Name VARCHAR(50),
    Phone_Number VARCHAR(15),
    Email VARCHAR(50),
    Address VARCHAR(100),
    CONSTRAINT CUSTOMER_PK PRIMARY KEY (Customer_ID)
);

CREATE TABLE RESERVATION
(
    Reservation_ID INT NOT NULL,
    Customer_ID INT,
    Number_Of_People INT,
    Time TIME,
    Date DATE,
    CONSTRAINT RESERVATION_PK PRIMARY KEY (Reservation_ID),
    CONSTRAINT RESERVATION_CUSTOMER_FK FOREIGN KEY (Customer_ID) REFERENCES CUSTOMER(Customer_ID)
        ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE TABLE_INFO
(
    Table_ID INT NOT NULL,
    Seating_Capacity INT,
    Table_Number INT,
    CONSTRAINT TABLE_INFO_PK PRIMARY KEY (Table_ID)
);

CREATE TABLE STAFF
(
    Staff_ID INT NOT NULL,
    First_Name VARCHAR(50),
    Last_Name VARCHAR(50),
    Role VARCHAR(50),
    Phone_Number VARCHAR(15),
    Email VARCHAR(50),
    Address VARCHAR(100),
    CONSTRAINT STAFF_PK PRIMARY KEY (Staff_ID)
);

CREATE TABLE RESERVES
(
    Reservation_ID INT NOT NULL,
    Table_ID INT NOT NULL,
    CONSTRAINT TABLE_RESERVATION_PK PRIMARY KEY (Reservation_ID, Table_ID),
    CONSTRAINT TABLE_RESERVATION_RESERVATION_FK FOREIGN KEY (Reservation_ID) REFERENCES RESERVATION(Reservation_ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT TABLE_RESERVATION_TABLE_FK FOREIGN KEY (Table_ID) REFERENCES TABLE_INFO(Table_ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ASSIGNED_TO
(
    Table_ID INT NOT NULL,
    Staff_ID INT NOT NULL,
    Time TIME NOT NULL,
    Date DATE NOT NULL,
    CONSTRAINT STAFF_ASSIGNMENT_PK PRIMARY KEY (Table_ID, Staff_ID, Time, Date),
    CONSTRAINT STAFF_ASSIGNMENT_TABLE_FK FOREIGN KEY (Table_ID) REFERENCES TABLE_INFO(Table_ID)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT STAFF_ASSIGNMENT_STAFF_FK FOREIGN KEY (Staff_ID) REFERENCES STAFF(Staff_ID)
        ON DELETE CASCADE ON UPDATE CASCADE
);